name: TruffleHog Secrets Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan-secrets:
    name: Run TruffleHog Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history for accurate scanning

      # Step 2: Run TruffleHog scan
      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified  # Optional: add custom arguments if needed

      # Step 3: Upload scan results as an artifact (optional)
      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-results
          path: ./trufflehog-results.json
